### PR TITLE
Master

### PR DESCRIPTION
**Pull request by JamesPondMC**
Add the plugin EZRanksLite and modify the plugins.json to include it.

### CODE REVIEW

**Comment by Fiiily** [comment]
I advise against this merge. EZRanksLite is highly configuration dependent and is unsupported.
(BTW I'm Ransomware in-game)

**Comment by lukechatton** [comment]
Dont see this plugin being viable on mchost due to no ingame configuration.

**Comment by Fiiily** [comment]
Close pull request, please.

**Comment by lukechatton** [comment]
After looking into the plugin, it looks like they added a significant amount of in game commands.

**Pull request merged**
